name: "Build"
on:
  push:
  pull_request:
  pull_request_target:


jobs:
  build-x86_64-linux:
    name: "build using nix"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: sumoduduk
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build package
        run: nix build --show-trace --log-lines 10000 --fallback

      - name : get version of app
        run : ./result/bin/reorgfolder --version

      - name: 'Tar files'
        run: tar -cvf reorgfolder.tar result/bin/reorgfolder


      - uses: actions/upload-artifact@v4
        with:
          name: reorgfolder-binary
          path: reorgfolder.tar

      - name: Run checks
        run: nix flake check --keep-going --all-systems

  test:
    name: "Test Reorgfolder"
    runs-on: ubuntu-latest
    needs: build-x86_64-linux
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: reorgfolder-binary
          path: ./

      - name: Extract tar file
        run: tar -xvf reorgfolder.tar

      - name: List directory structure
        run: ls -R

      - name: Run binary with --help
        run: ./reorgfolder --help

