name: "Build"
on:
  push:
  pull_request:
  pull_request_target:


jobs:
  build-x86_64-linux:
    name: "build using nix"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable


      - uses: cachix/cachix-action@v14
        with:
          name: sumoduduk
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build package
        run: nix build --show-trace --log-lines 10000 --fallback

      - uses: actions/upload-artifact@v4
        with:
          name: reorgfolder-binary
          path: result/bin/reorgfolder

  test:
    name: "Test Reorgfolder"
    runs-on: ubuntu-latest
    needs: build-x86_64-linux
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: reorgfolder-binary

      - name: List files in the directory
        run: ls -R

      - name: Make binary executable
        run: chmod +x ./result/bin/reorgfolder

      - name: Run Reorgfolder
        run: ./result/bin/reorgfolder --help
